### ISSUE TITLE
Discuss binder integration

### ISSUE THREAD

**Issue by choldgraf** [microsoft/gather#13]
Moving the Binder conversation here so that we're not just chatting in a closed PR :-)

re: repository size, it's OK to include extra cruft up to a certain point. If it's "can I include a bunch of notebooks that might be big-ish" that's totally fine. If it's "I want to include a 500MB dataset in my repository" that might be more of a performance hit. The biggest time-sink in Binder is the time it takes to "Docker pull" onto a node when somebody launches a repository for the first time on that node. After that, Binder uses the docker cache within the same node and it is much faster.

re: this repository or another repository, it can be whatever you'd like! Many people just use whichever repository they use for their documentation.

**Comment by andrewhead** [comment]
Good call on the move to an issue :-)

re: repository size, thanks for the clarification! Yeah, this is a pretty small repository (<10M of text and images) on mybinder.org, so I'll just publish this repo.

re: the right repository, great. With that rule of thumb, I'll keep the binder files in this repository for now and keep everything in one place.

**Comment by choldgraf** [comment]
cool! let me know if you'd like me to give some thoughts or pointers! You know what kinda notebook would best-show off Gather, so I'll leave that part t oyou :-)

**Comment by andrewhead** [comment]
sweet! already got a notebook and everything put together ^_^

I'm working on deploying to Binder with a workspace so the notebook opens right up. I found [ian-r-rose's helpful repo](https://github.com/ian-r-rose/binder-workspace-demo), though got hung up as Lab has a 404 for the workspace.json request.

Have you deployed Lab with a workspace configuration file before? If so, could I trouble you to take a quick look at the say [7 lines of code](https://github.com/microsoft/gather/pull/14/files) I've got to try it out to if anything obvious missing (like, do I need to use the Jupyter 1.0 alpha like ian-r-rose was)?

About to put this on pause for a few weeks of travel. Thanks again for the timely tipz, I'm pumped to have this repo contain a live online demo!

**Comment by choldgraf** [comment]
It seems like the binder does work, just not yet with the workspace pre-configured. E.g. this link will open jupyterlab w/ the notebook you've provided:

https://mybinder.org/v2/gh/microsoft/gather/add-binder-notebook?urlpath=lab/tree/binder%2FTry%20out%20nbgather.ipynb

Is there anything really specific in the workspace that isn't possible w/ this workflow?

**Comment by andrewhead** [comment]
Sure that works! Great catch!

**Comment by andrewhead** [comment]
Merged a [link to the Binder demo](https://gke.mybinder.org/v2/gh/microsoft/gather/master?urlpath=lab/tree/binder%2FTry%20out%20nbgather.ipynb) into the README in 253eab62f6d91d9a5a92650ace18d18cc6d7904a. The demo's live!

**Comment by choldgraf** [comment]
wahoo! welcome back from your trip :-)
