### ISSUE TITLE
Parser does not correctly set this.indents = [0] when this.indents is undefined

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/gather#18]
**Describe the bug**
In [python3.jison](https://github.com/microsoft/gather/blob/master/src/analysis/parse/python/python3.jison) on line 69, this.indents is incorrectly set. This corresponds to line 1064 in the generated python3.js file.
```typescript
if (this.indents == undefined) this.indents == [0]; // should be this.indents = [0]
```
This causes the parser to throw a `TypeError: Cannot read property 'length' of undefined at Object.anonymous [as performAction]` on the next line when the parser attempts to access this.indents.length:
```typescript
if (this.indents.length > 1) {
```

**Comment by andrewhead** [comment]
@joyceerhl is this fixed as of the merged pull request https://github.com/microsoft/gather/pull/19?

**Comment by joyceerhl** [comment]
Yep!
