### ISSUE TITLE
Function and class definition textSliceLines are incorrectly computed

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/gather#31]
**Describe the bug**
Originally reported in #23 for classes, but predates #28 
The line after a class or function definition is included twice in the gathered program. 

Here's an example illustrating the problem for funcdefs after executing the following program as a single cell in Jupyter:
```python
def foo():
    print("Hello") 
def bar(): 
    foo()
bar() 
``` 

The gathered program looks like this:
```python
def foo():
    print("Hello")
def bar():
def bar():
    foo()
bar()
bar()
```
Here's another example illustrating the problem for classes:
```python
class Foo():
    class Bar():
        pass
v=1
Foo().Bar()
```
The gathered program looks like this:
```python
class Foo():
    class Bar():
        pass
v=1
v=1
Foo().Bar()
```

**Additional information**
I'm somewhat out of my depth with debugging the parser, but it seems like the problem lies with the `ILocation` object that the parser returns, since for class and funcdefs, `loc.last_column === 0` and `loc.last_line` is the true last line incremented by one. `textSliceLines` is then incorrectly computed based on the values of `last_column` and `last_line` in `cellSlice.ts`--in this case, lines 3 and 5 are included twice. I've added unit tests that illustrate this behavior [here](https://github.com/joyceerhl/gather/commit/ca8c4a5ecf2dfc13184b348a9c7e1c9cd9555ed4).

If I'm not mistaken, this means a fix will involve modifying the parser to return an `ILocation` object whose `last_column` and `last_line` properties have accounted for the dedent. Alternatively, the `cellSlice.getTextSlice` logic could be updated.

**Comment by rdeline** [comment]
Thanks for catching this bug and a quick PR to fix it. I looked at the original code and the fix and found the whole method kind of confusing. I just submitted a version that's a little cleaner (I think). It didn't break any tests, so hopefully it's backward-compatible.
