### ISSUE TITLE
Icons for gathering not appearing in version browser

### ISSUE THREAD

**Issue by andrewhead** [microsoft/gather#34]
**Describe the bug**

The icons for "Open in notebook" and "Copy to clipboard" in the version browser are not appearing.

![image](https://user-images.githubusercontent.com/2358524/63540766-98117280-c4d1-11e9-8360-5a651063e3f5.png)

**To Reproduce**

Click on a variable or output, then click on "Gather to... Version Browser". You should be able to see that the icons are missing on the gather buttons.

**Expected behavior**

The icons should appear on the buttons, like so (screenshot taken from the version of gather currently hosted on BinderHub):

![image](https://user-images.githubusercontent.com/2358524/63540496-0570d380-c4d1-11e9-9b42-24a9e7981d49.png)

**Additional context**

This problem was probably introduced when gather started using Jupyter Lab libraries version >1.0 and the paths to the Jupyter icons changed. I already fixed the paths for the icons for the buttons in the Jupyter notebook toolbar in [this commit](https://github.com/microsoft/gather/commit/3c7989d0423226471f09d3473412e11fe9e7b3c3), so we probably just need to point the CSS classes of the buttons in the version browser interface to the classes defined in that commit.

**Comment by rdrahul** [comment]
Can i take this up?

**Comment by andrewhead** [comment]
Hi @rdrahul thanks for pinging ^_^ Yeah, please do! I'm happy to review a PR if you want to put something together.

**Comment by andrewhead** [comment]
Solved by @rdrahul in https://github.com/microsoft/gather/pull/36 🎉
